spring.application.name=backend

# postgre DB 설정
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/yeonny
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true

# fastAPI 설정
spring.config.import=optional:file:E:/jungle/week14-15_team03_ai_board_lab/backend/backend/.env[.properties]
python.ai.server.url=${PYTHON_AI_SERVER_URL}