spring.application.name=backend

# postgre DB 설정
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/yeonny
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true